use crate::models::intention::IntentionTree;

/// Format an IntentionTree as a markdown PR description.
pub fn format_pr_description(
    tree: &IntentionTree,
    branch: &str,
    commit_count: usize,
    ticket_ref: Option<&str>,
) -> String {
    let mut md = String::new();

    md.push_str("## Intention Tree\n\n");
    md.push_str(&format!(
        "> Extracted by IVC from {} commits on `{}`\n\n",
        commit_count, branch
    ));

    if let Some(ticket) = ticket_ref {
        md.push_str(&format!("**Ticket:** {}\n\n", ticket));
    }

    // Root intention
    md.push_str(&format!("### {}\n", tree.root.title));
    md.push_str(&format!(
        "**Type:** {} | **Reasoning:** {}\n\n",
        tree.root.intention_type, tree.root.reasoning
    ));

    if tree.children.is_empty() {
        md.push_str("---\n\n");
        md.push_str("*Generated by [IVC](https://github.com/katnyeung/ivc) — Intention Version Control*\n");
        return md;
    }

    // Sub-intentions
    md.push_str("### Sub-intentions\n\n");

    for (i, node) in tree.children.iter().enumerate() {
        md.push_str(&format!(
            "#### {}. {}\n",
            i + 1,
            node.intention.title
        ));
        md.push_str(&format!("- **Type:** {}\n", node.intention.intention_type));

        if !node.intention.files_changed.is_empty() {
            let files: Vec<String> = node
                .intention
                .files_changed
                .iter()
                .map(|f| format!("`{}`", f))
                .collect();
            md.push_str(&format!("- **Files:** {}\n", files.join(", ")));
        }

        md.push_str(&format!("- **Reasoning:** {}\n", node.intention.reasoning));

        if !node.depends_on.is_empty() {
            md.push_str(&format!(
                "- **Depends on:** {}\n",
                node.depends_on.join(", ")
            ));
        }

        if !node.intention.uncertainties.is_empty() {
            md.push_str("- **Uncertainties:**\n");
            for u in &node.intention.uncertainties {
                md.push_str(&format!("  - {}\n", u));
            }
        }

        if !node.intention.assumptions.is_empty() {
            md.push_str("- **Assumptions:**\n");
            for a in &node.intention.assumptions {
                md.push_str(&format!("  - {}\n", a));
            }
        }

        if !node.intention.alternatives_considered.is_empty() {
            md.push_str("- **Alternatives considered:**\n");
            for alt in &node.intention.alternatives_considered {
                md.push_str(&format!(
                    "  - {} (rejected: {})\n",
                    alt.approach, alt.rejected_because
                ));
            }
        }

        md.push('\n');
    }

    md.push_str("---\n\n");
    md.push_str("*Generated by [IVC](https://github.com/katnyeung/ivc) — Intention Version Control*\n");

    md
}
